### ISSUE TITLE
关于添加云朵图标功能性提示

### ISSUE THREAD

**Issue by babylife** [a2633063/SmartControl_Android_MQTT#10]
那个图标居然是要来更新MQTT地址的，我居然不知道。。。。。好吧，我就申请下健壮性需求，添加下云朵按钮的点击后的消息提醒，比如已经更新服务器地址等等。。。

谢谢老大。
顺便鄙视偷偷去商用的人。。。

**Comment by a2633063** [comment]
后续可能增加此提示

**Comment by a2633063** [comment]
已增加点按钮收到设备返回数据后会提示已设置mqtt服务器......
