### ISSUE TITLE
TC1固件刷写并成功配网后，客户端程序无法添加局域网内的设备

### ISSUE THREAD

**Issue by billysun76** [a2633063/SmartControl_Android_MQTT#15]
TC1固件刷写成功后，按照说明进行配网，配网成功后没有回显，但取消后路由器上可看到TC1已经连接WiFi并获得IP地址，这时使用增加设备-获取局域网设备，客户端没有任何反应，TC1并没有出现在列表里。固件使用最新的v0.10.3，客户端使用v0.10.3和V0.9，都是一样的现象。

**Comment by a2633063** [comment]
获取局域网设备是通过udp通信实现 可能存在通信不稳定的情况  请再次尝试获取
