### ISSUE TITLE
安卓app端刷新不及时

### ISSUE THREAD

**Issue by cordimax** [a2633063/SmartControl_Android_MQTT#16]
遇到这样一个问题，连接mqtt后，需要下拉刷新一下才能获得开关状态，功率是没问题的。能设置一下进入客户端自动刷新所有设备状态吗？
![TIM图片20190610085818](https://user-images.githubusercontent.com/23732555/59167643-d6e78b80-8b64-11e9-9ac9-f71f69cb79f9.jpg)

**Comment by a2633063** [comment]
有设置打开app自动刷新  但是通信不稳定导致数据可能未接受到  后续会更新mqtt的qos来保证数据收发稳定性
