### ISSUE TITLE
在魅族系统不定时闪退.

### ISSUE THREAD

**Issue by wmysh** [a2633063/SmartControl_Android_MQTT#17]
在魅族系统（android7.1.2 ; FLYME 7.9.5.28 beta）下会不定时闪退，闪退后APP恢复初始设置。完全无法使用。

0.10.3版本正常

**Comment by a2633063** [comment]
能否提供系统版本及log消息

**Comment by wmysh** [comment]
系统版本已经在上面提供，log由于身边没有安卓的开发环境，暂时没办法提供。可否告知较简易的提取方法？

**Comment by a2633063** [comment]
已经找到了闪退原因  麻烦帮忙确认一下  在闪退的时候 
https://api.github.com/repos/a2633063/SmartControl_Android_MQTT/releases/latest
这个链接能否打开

**Comment by wmysh** [comment]
原版确实打不开，在更新最新版本后没有复现。
