### ISSUE TITLE
android 4.4.4 提示，已停止运行

### ISSUE THREAD

**Issue by smart-z** [a2633063/SmartControl_Android_MQTT#18]
iOS用户手头只有个 android 4 的机器，装上打开就提示 “很抱歉，‘ZControl’已停止运行”，囧了个囧，有什么拯救的途径么？

**Comment by a2633063** [comment]
此issue重复 见#14 此问题暂时关闭 请关注#14
目前手上没有android 4.4的手机 所以暂时没有处理 后续会试试用模拟器来查找原因
