### ISSUE TITLE
设备运行时常单位

### ISSUE THREAD

**Issue by nxcjs** [a2633063/SmartControl_Android_MQTT#21]
设备运行时常为秒，实在是不好认，可否改为年月天小时分钟

**Comment by a2633063** [comment]
app上并不是有计算的上次开机时间....
那个就是用这个时间根据当前时间计算出来的

**Comment by nxcjs** [comment]
就是那个运行时间，是根据开机时间计算的？

**Comment by a2633063** [comment]
是的 控制页面的上次开机时间是根据接收到的设备运行总时间及当期时间计算得出

**Comment by a2633063** [comment]
版本v0.12.5已经修改,请关闭此issue
