### ISSUE TITLE
app通讯问题

### ISSUE THREAD

**Issue by xzlabs** [a2633063/SmartControl_Android_MQTT#23]
家里2个路由器，app通过tplink可以正常连接DC1,app通过斐讯k2p连接不到DC1。请问这一般是什么问题？

**Comment by a2633063** [comment]
在没有服务器的情况下,使用的是局域网udp广播,2个路由器已经不属于一个局域网了 所以无法通信
请在一个局域网下使用,否则请使用mqtt服务器

**Comment by xzlabs** [comment]
是在一个局域网的，我开始用的k2p（pandorabox），app一直连接不上DC1，配置不了wifi网络。没办法了，把tplink(k2p断电关闭)换上一下就连上了。再用k2p路由器，app还是连接不到DC1。
所以很迷惑，不知道这个需要路由器里面特殊设置一下吗？

**Comment by a2633063** [comment]
刷过的路由可能会阉割部分功能,除非更换配对方式,否则固件无解
