### ISSUE TITLE
zTC1不显示功率

### ISSUE THREAD

**Issue by Ilmiotesoro** [a2633063/SmartControl_Android_MQTT#24]
zTC1固件和APP均为最新版本，25号开始不显示功率。

**Comment by a2633063** [comment]
zTC1问题,目前判断部分可能是由于硬件问题,暂时不做处理关闭此issue

**Comment by Ilmiotesoro** [comment]
现在已经恢复了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zip Zhang"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 上午8:46
收件人: "a2633063/SmartControl_Android_MQTT"<SmartControl_Android_MQTT@noreply.github.com&gt;; 
抄送: "Ilmiotesoro"<513191215@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [a2633063/SmartControl_Android_MQTT] zTC1不显示功率 (#24)




zTC1问题,目前判断部分可能是由于硬件问题,暂时不做处理关闭此issue
 
&mdash;
