### ISSUE TITLE
安卓10，无法识别TC1各个开关状态

### ISSUE THREAD

**Issue by acceptin** [a2633063/SmartControl_Android_MQTT#26]
安卓版本：10
手机设备：小米8
设备：TC1
app版本：0.12.6
问题：升级到android 10后，打开app，无法识别各个开关状态（app显示全部关闭状态）与功耗，设备是有几个插座是开启状态。
状况一：打开其中一个插座01（设备那里的插座01是开启状态），然后关闭插座01，正常关闭。
状况二：打开插座02（设备里的02是关闭状态），正常打开

**Comment by a2633063** [comment]
下滑刷新状态
