### ISSUE TITLE
连接mqtt服务器后app里不能自动发现设备

### ISSUE THREAD

**Issue by maxmib** [a2633063/SmartControl_Android_MQTT#28]
安卓版本 10
手机 小米8
app版本 0.12.6
小米8不能通过局域网发现设备，就使用另一台安卓9的手机配置好m1并连接到mqtt服务器，然后小米8在app里连接到mqtt服务器，但app没有创建新的设备仍然获取不到m1的数据

**Comment by sunyh87** [comment]
刷完m1 好像对无线加密有要求，wpa2就连不上 wpa就好了 ，还有就是搭建好mqtt，app里设置好，m1用ttl设置好 ，app也是不能发现m1

**Comment by a2633063** [comment]
发现设备必须要app和设备在同一个局域网内执行  目前还不支持mqtt下发现设备
配置m1不能用ttl啊  直接用app配置 你用的是我的固件吗

**Comment by sunyh87** [comment]
> 发现设备必须要app和设备在同一个局域网内执行 目前还不支持mqtt下发现设备
> 配置m1不能用ttl啊 直接用app配置 你用的是我的固件吗

是你的固件啊，按着https://bbs.hassbian.com/forum.php?mod=viewthread&tid=4824&page=1&authorid=6533方法刷入 然后ttl配置wifi连接 然后手机app上发现不了M1,然后也搭建了mqtt 手机和m1都配置了 也发现不了  不知道怎么才能发现

**Comment by a2633063** [comment]
这不是我的固件 我的固件是zM1   github上能看到

**Comment by sunyh87** [comment]
> 这不是我的固件 我的固件是zM1 github上能看到

额 。。。。刷错了？那晚上再鼓捣一次

**Comment by sunyh87** [comment]
> 这不是我的固件 我的固件是zM1 github上能看到

成功识别添加了，昨晚刷的是那贴固件 哈哈
不过这连的wifi需要wpa加密，wpa2加密 就联网断断续续的 没法稳定在线
还有亮度拉到最低，就是关屏 wifi那标志还是有点微亮
把a1再刷了 能否配合m1使用？就像之前斐讯app那样

**Comment by a2633063** [comment]
a1配合m1 已经增加此功能  但是有可能不稳定 建议使用nr hass之类的自动化平台实现
关屏 wifi微亮是设计如此
