### ISSUE TITLE
无法添加设备，zM1

### ISSUE THREAD

**Issue by kenshinLost** [a2633063/SmartControl_Android_MQTT#29]
我刷了最新的固件后，配网很顺利。在使用zcontrol添加设备的时候，可以在mdns中发现设备，点击发现的设备后，跳转通过udp广播扫描附近的设置的窗口，并在下方跳出提示：zM1_xxxxx, xxxxxxxxx(这里是一串16进制字符串），这里udp扫描永远也扫描不到。返回主页，并没有添加成功。这里是不是我的操作有问题？

**Comment by a2633063** [comment]
看起来没问题
这算是个不是bug的bug吧
局域网设备是通过udp广播扫描设备. 某些路由器会对这个udp广播进行限制
mdns的发现设备是直接添加设备  但是还是加了udp的发现过程.

如果udp无法发现就算你通过mdns直接加入了设备列表.控制设备依然是通过udp来通信 同样无法控制  所以mdns依然增加udp扫描.
可以先用手机连2.4G网试试.
再确认下路由器的网络环境是否正常udp广播.
