### ISSUE TITLE
Enhancement Ruquest: add copy feature for MAC address

### ISSUE THREAD

**Issue by babylife** [a2633063/SmartControl_Android_MQTT#3]
add the copy MAC address feature when view the device information

**Comment by a2633063** [comment]
已增加此功能,但未release
请到以下路径下载(版本号未变)
https://github.com/a2633063/SmartControl_Android_MQTT/blob/master/app/release/app-release.apk

**Comment by babylife** [comment]
谢谢老大

**Comment by babylife** [comment]
已测试OK 谢谢
