### ISSUE TITLE
用光猫自带WIFI就不行，用路由器或者手机热点就正常，是哪里出了问题？

### ISSUE THREAD

**Issue by shangjiazi** [a2633063/SmartControl_Android_MQTT#30]
现在的光猫也是越做越牛了，5G都成标配了。完全没必要加路由了。
很遗憾，用光猫自带WIFI打开app发现不了设备，或者发现了控制不了，获取不到状态，等等，用路由器或者手机热点就正常，是哪里出了问题？

我看有人发说是加密方式，这光猫貌似还要破解才能改变

**Comment by a2633063** [comment]
app发现设备/局域网控制设备 是通过udp广播方式   可能是光猫对udp广播有限制  可以确认下这点

**Comment by shangjiazi** [comment]
已好，端口转发选择白名单
