### ISSUE TITLE
创建了一个命令行版本的SmartControl，可以在没有安卓手机的情况下激活

### ISSUE THREAD

**Issue by syhan** [a2633063/SmartControl_Android_MQTT#31]
从源码理解来的，目前可以激活tc1：）
https://github.com/syhan/smartcontrol-cli

**Comment by a2633063** [comment]
感觉我源码写得这么懒还来话时间理解啊...
通信协议是公开的..   直接看文档吧:   https://github.com/a2633063/zTC1/wiki/%E9%80%9A%E4%BF%A1%E5%8D%8F%E8%AE%AE

**Comment by syhan** [comment]
只是我发现需要首次通过udp的方式激活，之后通过mqtt怎么做都可以:)

**Comment by a2633063** [comment]
> 只是我发现需要首次通过udp的方式激活，之后通过mqtt怎么做都可以:)

激活并不需要一定要通过udp   
激活限制的只有插头开关控制, 
所有操作都可以通过mqtt或udp进行控制

**Comment by syhan** [comment]
嗯我说的不对，是将mqtt的配置发送给tc1需要通过udp来操作
