### ISSUE TITLE
手机端添加按钮触发结果验证状态提示

### ISSUE THREAD

**Issue by babylife** [a2633063/SmartControl_Android_MQTT#8]
健壮性需求： 由于使用udp触发，可能存在触发失败，可否在客户端触发开关命令后进行结果查询验证功能给与提示？

**Comment by a2633063** [comment]
udp仅为部分个人使用  不建议使用   针对udp以后不会考虑继续优化udp相关功能
建议使用mqtt服务器

**Comment by babylife** [comment]
好的，已经换用MQTT服务器，稳的不要不要的
